import { useState } from 'react';
import Badge from '../components/Badge';
import Modal from '../components/Modal';
import FormField from '../components/FormField';
import LoadingRow from '../components/LoadingRow';
import EmptyRow from '../components/EmptyRow';

export default function Books({ books, loading, message, onAddBook, onDeleteBook }) {
  const [showAdd, setShowAdd] = useState(false); const [search, setSearch] = useState(''); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: '', author: '', genre: '', price: '', publisher: '' }); const [errors, setErrors] = useState({});
  const filtered = books.filter((b) => (b.name || b.title || '').toLowerCase().includes(search.toLowerCase()) || (b.author || '').toLowerCase().includes(search.toLowerCase()));
  const add = async () => { const e = {}; if (!form.name.trim()) e.name = 'Title is required'; if (!form.author.trim()) e.author = 'Author is required'; if (!form.genre.trim()) e.genre = 'Genre is required'; if (form.price === '') e.price = 'Price is required'; if (!form.publisher.trim()) e.publisher = 'Publisher is required'; setErrors(e); if (Object.keys(e).length) return; setSaving(true); try { const ok = await onAddBook({ ...form, price: Number(form.price) }); if (ok) { setShowAdd(false); setForm({ name: '', author: '', genre: '', price: '', publisher: '' }); } } finally { setSaving(false); } };
  const del = async (id) => { if (window.confirm('Delete this book?')) await onDeleteBook(id); };

  return <div>
    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem', gap: 10, flexWrap: 'wrap' }}><h1 style={{ margin: 0, fontSize: 22 }}>Books</h1><div style={{ display: 'flex', gap: 8 }}><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder='Search books...' style={{ height: 32, borderRadius: 8, border: '1px solid var(--color-border-secondary)', padding: '0 10px' }} /><button onClick={() => setShowAdd(true)} style={{ height: 32, border: 'none', borderRadius: 8, padding: '0 12px', color: '#fff', background: '#0F6E56' }}>Add Book</button></div></div>
    {message ? <div style={{ marginBottom: 12, padding: '9px 14px', borderRadius: 8, background: message.type === 'success' ? 'var(--color-background-success)' : 'var(--color-background-danger)', color: message.type === 'success' ? 'var(--color-text-success)' : 'var(--color-text-danger)', fontSize: 13 }}>{message.text}</div> : null}
    <div style={{ background: '#fff', border: '1px solid var(--color-border-tertiary)', borderRadius: 12, overflow: 'hidden' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr style={{ background: 'var(--color-background-secondary)' }}>{['Book', 'Author', 'Genre', 'Price', 'Status', 'Actions'].map((h) => <th key={h} style={{ textAlign: 'left', padding: '10px 14px', fontSize: 11, color: 'var(--color-text-secondary)' }}>{h}</th>)}</tr></thead><tbody>{loading ? <LoadingRow cols={6} /> : filtered.length === 0 ? <EmptyRow cols={6} message='No books found' /> : filtered.map((b, i) => <tr key={b.id || i} style={{ borderBottom: '1px solid var(--color-border-tertiary)' }}><td style={{ padding: '10px 14px' }}>{b.name || b.title || `Book #${b.id}`}</td><td style={{ padding: '10px 14px' }}>{b.author || '—'}</td><td style={{ padding: '10px 14px' }}>{b.genre || '—'}</td><td style={{ padding: '10px 14px' }}>{b.price != null ? `$${b.price}` : '—'}</td><td style={{ padding: '10px 14px' }}><Badge type={b.issueDate ? 'warning' : 'success'}>{b.issueDate ? 'Issued' : 'Available'}</Badge></td><td style={{ padding: '10px 14px' }}><button onClick={() => del(b.id)}>Delete</button></td></tr>)}</tbody></table></div>
    {showAdd ? <Modal title='Add New Book' onClose={() => setShowAdd(false)}><FormField label='Book Title' value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} error={errors.name} /><FormField label='Author' value={form.author} onChange={(e) => setForm({ ...form, author: e.target.value })} error={errors.author} /><FormField label='Genre' value={form.genre} onChange={(e) => setForm({ ...form, genre: e.target.value })} error={errors.genre} /><FormField label='Publisher' value={form.publisher} onChange={(e) => setForm({ ...form, publisher: e.target.value })} error={errors.publisher} /><FormField label='Price ($)' type='number' value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} error={errors.price} /><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}><button onClick={() => setShowAdd(false)}>Cancel</button><button onClick={add}>{saving ? 'Saving...' : 'Add Book'}</button></div></Modal> : null}
  </div>;
}
